const { addProductsToCart, updateProductsInCart, deleteProductsFromCart, getCartItems } = require('../controllers/cartController');
const { addProducts, getProducts, updateProducts, deleteProducts, getProductsByCategories } = require('../controllers/productController');
const { addUser, userLogin, getUsers } = require('../controllers/userController');
const authMiddleware = require('../middleware/authMiddleware');
const routes = require('express').Router();
routes.post('/addUser', addUser);
routes.post('/getUsers',authMiddleware, getUsers);
routes.post('/userLogin', userLogin);
routes.post('/addProducts',authMiddleware, addProducts);
routes.post('/getProducts',authMiddleware, getProducts);
routes.post('/updateProducts',authMiddleware, updateProducts);
routes.post('/deleteProducts',authMiddleware, deleteProducts);
routes.post('/getProductsBycategory',authMiddleware, getProductsByCategories);
routes.post('/addProductsToCart',authMiddleware, addProductsToCart);
routes.post('/updateProductsInCart',authMiddleware, updateProductsInCart);
routes.post('/deleteProductsFromCart',authMiddleware, deleteProductsFromCart);
routes.post('/getCartItems',authMiddleware, getCartItems);
module.exports = routes;
